spring.application.name=mcp-server

spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.name=mcp-server
spring.ai.mcp.server.version=1.0.0

spring.main.web-application-type=none

spring.main.banner-mode=off
#logging.pattern.console=
logging.file.name=C:\\Users\\Sunil\\git\\mcp-server\\mcp-server\\log\\mcp-weather-stdio-server.log
logging.threshold.console=OFF
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

#logging.file.name=./model-context-protocol/weather/starter-stdio-server/target/mcp-weather-stdio-server.log

